/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cashier;

import java.util.ArrayList;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author WIN10 test
 */
public class Main extends javax.swing.JFrame {
    Connection conn;
    Statement st;
    ResultSet rs;
    String[] d = "jdbc:mysql://localhost:3306/depot,root".split(",");
    Object biaya;
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        showUser();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fastCalc = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        total = new javax.swing.JTextField();
        uangPembeli = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        kembalianP = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        calcBtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        sudahBtn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        fastCalc.setMinimumSize(new java.awt.Dimension(276, 231));

        total.setEditable(false);
        total.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        uangPembeli.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(uangPembeli)
                    .addComponent(total, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(uangPembeli, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("Calculate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        kembalianP.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        kembalianP.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout fastCalcLayout = new javax.swing.GroupLayout(fastCalc.getContentPane());
        fastCalc.getContentPane().setLayout(fastCalcLayout);
        fastCalcLayout.setHorizontalGroup(
            fastCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fastCalcLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fastCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fastCalcLayout.createSequentialGroup()
                        .addGap(0, 179, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(kembalianP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        fastCalcLayout.setVerticalGroup(
            fastCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fastCalcLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(kembalianP, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama Depan", "Nama Belakang", "Meja", "ListPesanan", "Total Biaya", "Kode Pembayaran", "Status Pembayaran"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        calcBtn.setText("Calculator");
        calcBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcBtnActionPerformed(evt);
            }
        });

        jButton2.setText("Fast Calculate");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        sudahBtn.setText("Sudah");
        sudahBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sudahBtnActionPerformed(evt);
            }
        });

        jButton3.setText("Refresh");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 849, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(calcBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sudahBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calcBtn)
                    .addComponent(jButton2)
                    .addComponent(sudahBtn)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calcBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcBtnActionPerformed
        // TODO add your handling code here:
        calc c = new calc();
        
        c.setVisible(true);
    }//GEN-LAST:event_calcBtnActionPerformed

    private void sudahBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sudahBtnActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        Object value = jTable1.getValueAt(row, 0);
        try {
            conn = DriverManager.getConnection(d[0],d[1],"");
            PreparedStatement ps = conn.prepareStatement("UPDATE pembayaran_inner SET statusPembayaran = 1 WHERE idPembayaran = "+value);
            ps.executeUpdate();
            refreshData();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane,"Edit Gagal!");
            System.out.println(e);
        }
    }//GEN-LAST:event_sudahBtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        fastCalc();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Integer up = new Integer(uangPembeli.getText());
        Integer tb = new Integer(biaya.toString());
        if(up<tb){
            JOptionPane.showMessageDialog(rootPane, "Maaf, uang pembeli kurang");
        }
        else{
            int kembalian = tb-up;
            kembalianP.setText(kembalian+" ");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        refreshData();
    }//GEN-LAST:event_jButton3ActionPerformed

    public void refreshData(){
        DefaultTableModel mdl = (DefaultTableModel)jTable1.getModel();
        mdl.setRowCount(0);
        showUser();
 
    }
    
    public ArrayList<CashierUser> userList(){
        ArrayList<CashierUser> userList = new ArrayList();
        try {
            conn = DriverManager.getConnection(d[0],d[1],"");
            st = conn.createStatement();
            rs = st.executeQuery("SELECT * FROM pembayaran_inner WHERE statusPembayaran = 0");
            CashierUser user;
            while(rs.next()){
                user = new CashierUser(rs.getInt(1),rs.getString(2),rs.getString(3),rs.getInt(4),rs.getString(5),rs.getInt(6),rs.getString(7),rs.getInt(8));
                userList.add(user);
            }
        } catch (Exception e) {
            System.out.println("aaa"+e);
        }
        return userList;
    }
   
    public void showUser(){
        ArrayList<CashierUser> list = userList();
        DefaultTableModel mdl = (DefaultTableModel)jTable1.getModel();
        
        Object[] col = new Object[8];
        for(int i=0;i<list.size();i++){
            col[0] = list.get(i).getId();
            col[1] = list.get(i).getfName();
            col[2] = list.get(i).getlName();
            col[3] = list.get(i).getnomorMeja();
            col[4] = list.get(i).getListPesanan();
            col[5] = list.get(i).getTotalBiaya();
            col[6] = list.get(i).getKodePembayaran();
            col[7] = list.get(i).getStatusPembayaran();
            mdl.addRow(col);
        }
    }
    
    public void fastCalc(){
        int row = jTable1.getSelectedRow();
        biaya = jTable1.getValueAt(row,5);
        fastCalc.setVisible(true);
        total.setText(biaya.toString());
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calcBtn;
    private javax.swing.JFrame fastCalc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel kembalianP;
    private javax.swing.JButton sudahBtn;
    private javax.swing.JTextField total;
    private javax.swing.JTextField uangPembeli;
    // End of variables declaration//GEN-END:variables
}
