
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.*;
import java.time.LocalDate;
import java.util.Calendar;
import java.util.Properties;
import java.util.Random;
import javax.swing.JOptionPane; 
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author WIN10 test
 */
public class LoginFrame extends javax.swing.JFrame {
    /**
     * Creates new form LoginFrame
     */
    String id;
    String pass = new String("");
    String[] td;
    String theDate;
    char[] p;
    String radio;
    String[] db = "jdbc:mysql://putraput.eu.org:3306/depot,putra,delfira26".split(",");
    static Connection conn;
        Statement st = null;
        ResultSet rs = null;
    String query = null;
    Properties gg = new Properties();
    InputStream fr;
    LocalDate localD;
    int resultrow;
    MainFrame mf;
    public LoginFrame() {
        Konektor k = new Konektor(db);
        conn = k.getConn();
        getDate();
        theDate = td[0]+td[1]+td[2];
        initComponents();
        System.out.println(theDate);
        Randomsess();
        Session();
    }
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        loginBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        custRadio = new javax.swing.JRadioButton();
        makananRadio = new javax.swing.JRadioButton();
        minumanRadio = new javax.swing.JRadioButton();
        reportRadio = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        chckSess = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manager Login");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Username");

        jLabel3.setText("Password");

        usernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFieldActionPerformed(evt);
            }
        });

        passwordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passwordFieldKeyTyped(evt);
            }
        });

        loginBtn.setText("Log in");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Manage"));

        custRadio.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(custRadio);
        custRadio.setText("Customer");

        makananRadio.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(makananRadio);
        makananRadio.setText("Makanan");

        minumanRadio.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(minumanRadio);
        minumanRadio.setText("Minuman");

        reportRadio.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(reportRadio);
        reportRadio.setSelected(true);
        reportRadio.setText("Report");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(custRadio)
                    .addComponent(reportRadio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minumanRadio, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(makananRadio, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reportRadio)
                    .addComponent(makananRadio))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(custRadio)
                    .addComponent(minumanRadio)))
        );

        makananRadio.getAccessibleContext().setAccessibleName("Manage");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 36)); // NOI18N
        jLabel1.setText("Manager Login");

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\WIN10 test\\Downloads\\administrator.png")); // NOI18N
        jLabel4.setPreferredSize(new java.awt.Dimension(550, 512));

        chckSess.setText("Check Session");
        chckSess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chckSessActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(20, 20, 20)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(passwordField)
                                    .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(chckSess)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(loginBtn)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginBtn)
                    .addComponent(chckSess))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setText("Resto Apps v1.0.1 © 2017 - All Right Reserved");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldActionPerformed

    public void radioBtnManage(){
        if(reportRadio.isSelected()){
            MainFrame report = new MainFrame();
            report.setVisible(true);
            this.dispose();
        }
        else if(custRadio.isSelected()){
            CustFrame cust = new CustFrame();
            cust.setVisible(true);
            this.dispose();
        }
        else if(makananRadio.isSelected()){
            MakananFrame makanan = new MakananFrame();
            makanan.setVisible(true);
            this.dispose();
        }
        else if(minumanRadio.isSelected()){
            MinumanFrame minuman = new MinumanFrame();
            minuman.setVisible(true);
            this.dispose();
        }
    }
    
    
    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        
        if(usernameField.getText().length()==0 || passwordField.getPassword().equals(null)){
            JOptionPane.showMessageDialog(this, "Harap Masukan Username atau Password!");
        }
        else{
        try {
            p = passwordField.getPassword();
            
            //getPassword
            for(int i=0;i<p.length;i++){
                pass += p[i];
            }
            
            //prevent sql Injection
            if(pass.indexOf("'")!=-1){
                pass = null;
            }
              
            query = "SELECT * FROM datamanager WHERE username = '"+usernameField.getText()+"' AND password = '"+pass+"'";
            System.out.println(query+"the p = "+pass);
            st = conn.createStatement();
            rs = st.executeQuery(query);
            rs.next();
            if(rs.getRow()==1){
                gg.setProperty("lastuser", usernameField.getText());
                FileOutputStream os = new FileOutputStream("myProperties.properties");
                gg.store(os, null);
                JOptionPane.showMessageDialog(this, "Success!");
                System.out.println(radio);
                Randomsess();
                savetoDB();
                radioBtnManage();
                this.dispose();
            }
            else{
                JOptionPane.showMessageDialog(this, "Username / Password Salah!");
                pass = "";
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error!");
            System.out.println(e.toString());
        }    
        }
    }//GEN-LAST:event_loginBtnActionPerformed

    public void Randomsess(){
        final String alphabet = "0123456789ABCDE";
        final int N = alphabet.length();
        String zz = "";
        Random r = new Random();

        for (int i = 0; i < 10; i++) {
            System.out.print(alphabet.charAt(r.nextInt(N)));
            zz += alphabet.charAt(r.nextInt(N));
        }
            id = zz;
    }
    
    public void Session(){
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            
            fr = new FileInputStream("myProperties.properties");
            gg.load(fr);
            if(gg.getProperty("sessid") != null || gg.getProperty("lastuser") != null || gg.getProperty("lastlogin") != null){
                //os
                System.out.println("else Worked : "+gg.getProperty("sessid"));
                System.out.println(gg.getProperty("lastlogin")+" - "+theDate.toString());
                if(gg.getProperty("lastlogin")!=theDate.toString()){
                    FileOutputStream os = new FileOutputStream("myProperties.properties");
                    gg.setProperty("lastlogin", theDate);
                    System.out.println("Lastlogin value changed to "+theDate);
                    gg.store(os, null);
                }
            }
            else{
                FileOutputStream os = new FileOutputStream("myProperties.properties");
                System.out.println("else");
                gg.setProperty("sessid", id);
                if(gg.getProperty("lastlogin")!=theDate.toString()){
                    gg.setProperty("lastlogin", theDate);
                    System.out.println("Lastlogin value changed to "+theDate);
                }
                System.out.println("if Worked : "+gg.getProperty("sessid"));
                gg.store(os, null);
            }
        } catch (IOException e) {
            System.out.println(e);
        }
    }
    
    public void getDate(){
        Calendar calendar = Calendar.getInstance();
        java.util.Date currentDate = calendar.getTime();
        java.sql.Date date = new java.sql.Date(currentDate.getTime());
        String as = date.toString();
        td = as.split("-");
    }
    
    public void savetoDB(){
        try {
            fr = new FileInputStream("myProperties.properties");
            gg.load(fr);
            query = "UPDATE `datamanager` SET `lastLogin` = '"+theDate+"',`session` = '"+gg.getProperty("sessid")+"' WHERE `datamanager`.`username` = '"+usernameField.getText()+"'";
              
            System.out.println(query);
            PreparedStatement updateEXP = conn.prepareStatement(query);
            updateEXP.executeUpdate();
        } catch (Exception e) {
            System.out.println(e);
        }
        
    }
    
    private void passwordFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordFieldKeyTyped
        // TODO add your handling code here:
        if(passwordField.getPassword().length>15){
            evt.consume();
        }
    }//GEN-LAST:event_passwordFieldKeyTyped

    private void chckSessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chckSessActionPerformed
        // TODO add your handling code here:
        checkSession();
    }//GEN-LAST:event_chckSessActionPerformed
        
    public void checkSession(){
       try {
             
           fr = new FileInputStream("myProperties.properties");
           gg.load(fr);
           String sessid = gg.getProperty("sessid");
           String lastuser = new String(gg.getProperty("lastuser"));
           
           st = conn.createStatement();
           rs = st.executeQuery("SELECT * FROM datamanager WHERE username = '"+lastuser+"' AND session = '"+sessid+"' AND lastlogin = '"+theDate+"'");
           rs.next();
           Thread.sleep(6000);
           if(rs.getRow()==1){
               radioBtnManage();
           }
           
           else{    
               JOptionPane.showMessageDialog(this, "Maaf sesi anda expired, silahkan login ulang");
               PreparedStatement ps = conn.prepareStatement("UPDATE `datamanager` SET `lastLogin` = '0',`session` = '0' WHERE `datamanager`.`username` = '"+lastuser+"'");
               ps.executeUpdate();
               gg.setProperty("sessid", id);
               gg.setProperty("lastuser", "");
               FileOutputStream os = new FileOutputStream("myProperties.properties");
               gg.store(os, null);
               chckSess.setEnabled(false);
           }
       } catch (Exception e) {
           System.out.println("aaaa"+e);
       }
   }
   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton chckSess;
    private javax.swing.JRadioButton custRadio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton loginBtn;
    private javax.swing.JRadioButton makananRadio;
    private javax.swing.JRadioButton minumanRadio;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JRadioButton reportRadio;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables

}
